### ISSUE TITLE
Issues: Morning session group

### ISSUE THREAD

**Issue by this-ezzy** [anthonymr/Todo-list#7]
Hi @anthonymr, Your project is really good and meets all necessary requirements.
Your project is well structured as well.
 Congratulations! 🎉
I just have one suggestion:

# Suggestion
- I would suggest you remove the sortedTask method in the TodoList class inside the todolists module, as this does the same function as the resetIndex method in the same class.

**Comment by anthonymr** [comment]
Hi @Ezzywealth, thank you for that clever suggestion. The change was applied in the last commit.
